/**
 * Forge-Zero model catalogue.
 *
 * Everything in this file exists to answer one question: *given a free API key
 * for model X, what does the prompt have to look like so that X actually
 * finishes the job?* A single-file HTML app generated by Gemini 3 Flash needs a
 * different prompt than the same app generated by Llama 3.1 8B on a 6K-token
 * per-minute Groq key.
 *
 * Therefore each profile carries three kinds of truth:
 *   1. Hard ceilings  — contextWindow, outputCeiling, freeTier rate limits.
 *   2. Capabilities   — what API features the endpoint honours (JSON schema,
 *                       system role, streaming, stop sequences).
 *   3. Behavioural quirks — observed failure modes that change the wording of
 *                       the prompt (see QUIRKS for the controlled vocabulary).
 *
 * Quirks are codes, not prose: the composer branches on them, so adding a new
 * model means filling in a row, not writing new generation logic.
 *
 * Limits here were verified against provider docs and independent measurements
 * in September 2026. Free tiers are the most volatile numbers in this industry;
 * every profile exposes `verifiedAt` and the UI surfaces it so a stale row is
 * visible instead of silently wrong.
 */

export const VERIFIED_AT = '2026-09';

/** Controlled vocabulary of prompt-relevant failure modes. */
export const QUIRKS = {
  preamble: {
    label: 'Narrates before code',
    detail:
      'Prefaces output with "Here is the app…" and postambles with explanations, wasting output budget and breaking copy-paste.',
  },
  truncation: {
    label: 'Stops mid-file',
    detail:
      'Silently ends long generations, often inside a function, and then claims the file is complete.',
  },
  'markdown-creep': {
    label: 'Wraps files in prose fences',
    detail:
      'Emits several ```js fences with commentary between them instead of one raw file, so mechanical reassembly fails.',
  },
  'reasoning-tax': {
    label: 'Charges for thinking',
    detail:
      'Reasoning model: chain-of-thought is billed against the same output ceiling as the code.',
  },
  drift: {
    label: 'Instruction drift',
    detail:
      'Loses track of the rules at the top of a long prompt; contracts must be restated near the end.',
  },
  terse: {
    label: 'Under-delivers',
    detail:
      'Replaces requested behaviour with a stub "for brevity" and calls it done.',
  },
  'over-abstract': {
    label: 'Invents frameworks',
    detail:
      'Sprinkles factories, providers and generic helpers where a plain function was wanted.',
  },
  'hallucinated-api': {
    label: 'Invents library APIs',
    detail:
      'Calls plausible-but-nonexistent methods on CDN libraries and current syntax on older pinned versions.',
  },
  'unicode-wobble': {
    label: 'Mangles non-ASCII',
    detail: 'Corrupts emoji and box-drawing characters inside string literals.',
  },
  'summary-addict': {
    label: 'Summarises instead of emitting',
    detail:
      'Answers "add a delete button" with a description of the change rather than the changed file.',
  },
  'self-consistent': {
    label: 'Good at self-review',
    detail: 'Reliably uses an appended acceptance checklist to catch its own bugs.',
  },
  'fast-cheap': {
    label: 'High free throughput',
    detail: 'Generous tokens-per-day for its class; safe for multi-stage plans.',
  },
};

/** Capability flags gate which prompt *protocols* we are allowed to demand. */
const CAP = (over = {}) => ({
  systemRole: true,
  jsonMode: false,
  jsonSchema: false,
  streaming: true,
  temperature: true,
  topP: true,
  stop: true,
  seed: false,
  tools: false,
  vision: false,
  ...over,
});

export const PROVIDERS = [
  {
    id: 'google',
    label: 'Google AI Studio',
    family: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    keyUrl: 'https://aistudio.google.com/app/apikey',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    authHeader: 'x-goog-api-key',
    tierNote:
      'Largest free daily request budget of any capable coding model. Free tier trains on prompts outside EU/UK/EEA — never paste secrets.',
    models: [
      {
        id: 'gemini-2.5-flash',
        label: 'Gemini 2.5 Flash',
        contextWindow: 1_048_576,
        outputCeiling: 65_536,
        quality: 8.4,
        speedTps: 180,
        verifiedAt: VERIFIED_AT,
        supports: CAP({
          jsonMode: true,
          jsonSchema: true,
          seed: true,
          tools: true,
          vision: true,
        }),
        freeTier: {
          rpm: 10,
          rpd: 250,
          tpm: 250_000,
          tpd: null,
          cardRequired: false,
          trainsOnData: true,
          reset: 'midnight Pacific',
        },
        quirks: ['reasoning-tax', 'self-consistent'],
        sampling: { temperature: 0.4, topP: 0.95 },
        bestFor: ['long-context', 'full-stack', 'single-file'],
      },
      {
        id: 'gemini-2.5-flash-lite',
        label: 'Gemini 2.5 Flash-Lite',
        contextWindow: 1_048_576,
        outputCeiling: 8_192,
        quality: 6.6,
        speedTps: 260,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, jsonSchema: true, vision: true }),
        freeTier: {
          rpm: 15,
          rpd: 1000,
          tpm: 250_000,
          tpd: null,
          cardRequired: false,
          trainsOnData: true,
          reset: 'midnight Pacific',
        },
        quirks: ['terse', 'truncation', 'drift'],
        sampling: { temperature: 0.3, topP: 0.9 },
        bestFor: ['single-file', 'high-volume', 'repairs'],
      },
      {
        id: 'gemini-3-flash',
        label: 'Gemini 3 Flash',
        contextWindow: 1_048_576,
        outputCeiling: 65_536,
        quality: 9.1,
        speedTps: 150,
        verifiedAt: VERIFIED_AT,
        supports: CAP({
          jsonMode: true,
          jsonSchema: true,
          tools: true,
          vision: true,
          seed: true,
        }),
        freeTier: {
          rpm: 10,
          rpd: 1500,
          tpm: 1_000_000,
          tpd: null,
          cardRequired: false,
          trainsOnData: true,
          reset: 'midnight Pacific',
        },
        quirks: ['reasoning-tax', 'self-consistent'],
        sampling: { temperature: 0.35, topP: 0.95 },
        bestFor: ['full-stack', 'single-file', 'long-context', 'plan-first'],
      },
    ],
  },
  {
    id: 'groq',
    label: 'Groq',
    family: 'openai',
    baseUrl: 'https://api.groq.com/openai/v1',
    keyUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs/rate-limits',
    authHeader: 'authorization',
    tierNote:
      'Fastest free inference available, which makes multi-stage plans feel instant. TPM is the binding constraint: a 6K-token stage takes a full minute of budget.',
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        label: 'Llama 3.3 70B',
        contextWindow: 128_000,
        outputCeiling: 8_192,
        quality: 7.9,
        speedTps: 320,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true }),
        freeTier: {
          rpm: 30,
          rpd: 1000,
          tpm: 6_000,
          tpd: 500_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['preamble', 'drift', 'self-consistent'],
        sampling: { temperature: 0.2, topP: 0.9 },
        bestFor: ['single-file', 'repairs', 'balanced'],
      },
      {
        id: 'llama-3.1-8b-instant',
        label: 'Llama 3.1 8B Instant',
        contextWindow: 128_000,
        outputCeiling: 4_096,
        quality: 5.4,
        speedTps: 720,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true }),
        freeTier: {
          rpm: 30,
          rpd: 14_400,
          tpm: 6_000,
          tpd: 100_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['preamble', 'truncation', 'terse', 'over-abstract', 'drift', 'hallucinated-api', 'summary-addict'],
        sampling: { temperature: 0.1, topP: 0.85 },
        bestFor: ['scaffold-only', 'tiny-apps', 'repairs'],
      },
      {
        id: 'openai/gpt-oss-120b',
        label: 'GPT-OSS 120B',
        contextWindow: 131_072,
        outputCeiling: 16_384,
        quality: 8.6,
        speedTps: 240,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 30,
          rpd: 1000,
          tpm: 12_000,
          tpd: 500_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['reasoning-tax', 'self-consistent'],
        sampling: { temperature: 0.2 },
        bestFor: ['full-stack', 'single-file', 'plan-first'],
      },
      {
        id: 'meta-llama/llama-4-scout-17b-16e-instruct',
        label: 'Llama 4 Scout 17B',
        contextWindow: 128_000,
        outputCeiling: 8_192,
        quality: 6.2,
        speedTps: 480,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, vision: true }),
        freeTier: {
          rpm: 30,
          rpd: 1000,
          tpm: 6_000,
          tpd: 300_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['preamble', 'terse', 'hallucinated-api', 'drift'],
        sampling: { temperature: 0.15, topP: 0.9 },
        bestFor: ['single-file', 'scaffold-only'],
      },
    ],
  },
  {
    id: 'cerebras',
    label: 'Cerebras Inference',
    family: 'openai',
    baseUrl: 'https://api.cerebras.ai/v1',
    keyUrl: 'https://cloud.cerebras.ai',
    docsUrl: 'https://inference-docs.cerebras.ai/api-reference/chat-completions',
    authHeader: 'authorization',
    tierNote:
      '1M free tokens per day at wafer-scale speed. The generous daily token ceiling is what makes a 9-stage full-stack plan affordable on a single key.',
    models: [
      {
        id: 'gpt-oss-120b',
        label: 'GPT-OSS 120B (Cerebras)',
        contextWindow: 131_072,
        outputCeiling: 16_384,
        quality: 8.5,
        speedTps: 550,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true }),
        freeTier: {
          rpm: 30,
          rpd: 14_400,
          tpm: 100_000,
          tpd: 1_000_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'rolling day',
        },
        quirks: ['reasoning-tax', 'fast-cheap', 'self-consistent'],
        sampling: { temperature: 0.2 },
        bestFor: ['full-stack', 'single-file', 'plan-first'],
      },
      {
        id: 'qwen-3-235b-a22b-instruct-2507',
        label: 'Qwen3 235B A22B Instruct',
        contextWindow: 131_072,
        outputCeiling: 16_384,
        quality: 8.7,
        speedTps: 520,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 30,
          rpd: 14_400,
          tpm: 100_000,
          tpd: 1_000_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'rolling day',
        },
        quirks: ['preamble', 'fast-cheap', 'over-abstract'],
        sampling: { temperature: 0.25, topP: 0.9 },
        bestFor: ['full-stack', 'single-file'],
      },
      {
        id: 'llama-3.1-8b',
        label: 'Llama 3.1 8B (Cerebras)',
        contextWindow: 128_000,
        outputCeiling: 8_192,
        quality: 5.2,
        speedTps: 1900,
        verifiedAt: VERIFIED_AT,
        freeTier: {
          rpm: 30,
          rpd: 14_400,
          tpm: 100_000,
          tpd: 1_000_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'rolling day',
        },
        supports: CAP({}),
        quirks: ['preamble', 'truncation', 'terse', 'drift', 'hallucinated-api', 'summary-addict'],
        sampling: { temperature: 0.1 },
        bestFor: ['scaffold-only', 'tiny-apps', 'repairs'],
      },
    ],
  },
  {
    id: 'openrouter',
    label: 'OpenRouter (free models)',
    family: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    keyUrl: 'https://openrouter.ai/settings/keys',
    docsUrl: 'https://openrouter.ai/docs/api-reference/limits',
    authHeader: 'authorization',
    tierNote:
      'One key, a rotating roster of `:free` models. Free models are capped at 50 requests/day until you have ever bought $10 of credits (then 1,000/day). Roster churns monthly — treat ids as disposable.',
    models: [
      {
        id: 'nvidia/nemotron-3-super-120b-a12b:free',
        label: 'Nemotron 3 Super 120B (free)',
        contextWindow: 1_000_000,
        outputCeiling: 32_768,
        quality: 8.8,
        speedTps: 90,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 20,
          rpd: 50,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['reasoning-tax', 'truncation', 'self-consistent'],
        sampling: { temperature: 0.2 },
        bestFor: ['full-stack', 'long-context', 'plan-first'],
      },
      {
        id: 'poolside/laguna-m.1:free',
        label: 'Poolside Laguna M.1 (free)',
        contextWindow: 262_144,
        outputCeiling: 16_384,
        quality: 8.9,
        speedTps: 70,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 20,
          rpd: 50,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['reasoning-tax', 'preamble'],
        sampling: { temperature: 0.15 },
        bestFor: ['full-stack', 'single-file', 'refactors'],
      },
      {
        id: 'cohere/north-mini-code:free',
        label: 'Cohere North Mini Code (free)',
        contextWindow: 256_000,
        outputCeiling: 16_384,
        quality: 8.0,
        speedTps: 120,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 20,
          rpd: 50,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['preamble', 'self-consistent'],
        sampling: { temperature: 0.2 },
        bestFor: ['full-stack', 'single-file'],
      },
      {
        id: 'openai/gpt-oss-20b:free',
        label: 'GPT-OSS 20B (free)',
        contextWindow: 131_072,
        outputCeiling: 8_192,
        quality: 7.0,
        speedTps: 150,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true }),
        freeTier: {
          rpm: 20,
          rpd: 50,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['reasoning-tax', 'truncation'],
        sampling: { temperature: 0.2 },
        bestFor: ['single-file', 'balanced'],
      },
      {
        id: 'google/gemma-4-31b-it:free',
        label: 'Gemma 4 31B (free)',
        contextWindow: 262_144,
        outputCeiling: 8_192,
        quality: 6.8,
        speedTps: 140,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, vision: true }),
        freeTier: {
          rpm: 20,
          rpd: 50,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['preamble', 'terse', 'drift', 'unicode-wobble', 'markdown-creep'],
        sampling: { temperature: 0.3 },
        bestFor: ['single-file', 'tiny-apps'],
      },
      {
        id: 'meta-llama/llama-3.3-70b-instruct:free',
        label: 'Llama 3.3 70B Instruct (free)',
        contextWindow: 131_072,
        outputCeiling: 8_192,
        quality: 7.6,
        speedTps: 110,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true }),
        freeTier: {
          rpm: 20,
          rpd: 50,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['preamble', 'drift', 'over-abstract'],
        sampling: { temperature: 0.2, topP: 0.9 },
        bestFor: ['single-file', 'repairs'],
      },
    ],
  },
  {
    id: 'mistral',
    label: 'Mistral La Plateforme',
    family: 'mistral',
    baseUrl: 'https://api.mistral.ai/v1',
    keyUrl: 'https://console.mistral.ai/api-keys',
    docsUrl: 'https://docs.mistral.ai/getting-started/models/models_overview',
    authHeader: 'authorization',
    tierNote:
      'Experiment tier: 1 request/second and a huge monthly token pool, but it trains on your prompts. Best strict-JSON schema support of any free tier — use it for the plan stage.',
    models: [
      {
        id: 'devstral-latest',
        label: 'Devstral',
        contextWindow: 128_000,
        outputCeiling: 32_768,
        quality: 8.9,
        speedTps: 110,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, jsonSchema: true, tools: true }),
        freeTier: {
          rpm: 60,
          rpd: null,
          tpm: 500_000,
          tpd: 33_000_000,
          cardRequired: false,
          trainsOnData: true,
          reset: 'calendar month',
        },
        quirks: ['preamble', 'self-consistent', 'fast-cheap'],
        sampling: { temperature: 0.15, topP: 0.9 },
        bestFor: ['full-stack', 'single-file', 'refactors'],
      },
      {
        id: 'codestral-latest',
        label: 'Codestral',
        contextWindow: 256_000,
        outputCeiling: 32_768,
        quality: 8.6,
        speedTps: 95,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, jsonSchema: true, tools: true }),
        freeTier: {
          rpm: 60,
          rpd: null,
          tpm: 500_000,
          tpd: 33_000_000,
          cardRequired: false,
          trainsOnData: true,
          reset: 'calendar month',
        },
        quirks: ['preamble', 'terse'],
        sampling: { temperature: 0.1 },
        bestFor: ['full-stack', 'refactors'],
      },
      {
        id: 'mistral-small-latest',
        label: 'Mistral Small 3.1',
        contextWindow: 128_000,
        outputCeiling: 8_192,
        quality: 7.1,
        speedTps: 160,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, jsonSchema: true, vision: true }),
        freeTier: {
          rpm: 60,
          rpd: null,
          tpm: 500_000,
          tpd: 33_000_000,
          cardRequired: false,
          trainsOnData: true,
          reset: 'calendar month',
        },
        quirks: ['preamble', 'truncation', 'drift', 'markdown-creep'],
        sampling: { temperature: 0.2 },
        bestFor: ['single-file', 'repairs'],
      },
      {
        id: 'open-mistral-nemo',
        label: 'Mistral Nemo 12B (open)',
        contextWindow: 128_000,
        outputCeiling: 4_096,
        quality: 5.6,
        speedTps: 210,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, jsonSchema: true }),
        freeTier: {
          rpm: 60,
          rpd: null,
          tpm: 500_000,
          tpd: 33_000_000,
          cardRequired: false,
          trainsOnData: true,
          reset: 'calendar month',
        },
        quirks: ['preamble', 'truncation', 'terse', 'hallucinated-api', 'over-abstract'],
        sampling: { temperature: 0.1 },
        bestFor: ['scaffold-only', 'tiny-apps'],
      },
    ],
  },
  {
    id: 'nvidia',
    label: 'NVIDIA NIM',
    family: 'openai',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    keyUrl: 'https://build.nvidia.com',
    docsUrl: 'https://docs.api.nvidia.com/nim/reference',
    authHeader: 'authorization',
    tierNote:
      'Free developer credits against a large open-model catalogue at ~40 RPM. Endpoints are occasionally saturated; always keep a fallback model for the same brief.',
    models: [
      {
        id: 'deepseek-ai/deepseek-v3.2',
        label: 'DeepSeek V3.2 (NIM)',
        contextWindow: 163_840,
        outputCeiling: 32_768,
        quality: 8.8,
        speedTps: 60,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 40,
          rpd: 1000,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'credit-based',
        },
        quirks: ['reasoning-tax', 'self-consistent', 'over-abstract'],
        sampling: { temperature: 0.2 },
        bestFor: ['full-stack', 'plan-first'],
      },
      {
        id: 'mistralai/devstral-2-123b',
        label: 'Devstral 2 123B (NIM)',
        contextWindow: 262_144,
        outputCeiling: 32_768,
        quality: 8.7,
        speedTps: 75,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 40,
          rpd: 1000,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'credit-based',
        },
        quirks: ['preamble', 'self-consistent'],
        sampling: { temperature: 0.15 },
        bestFor: ['full-stack', 'single-file'],
      },
    ],
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare Workers AI',
    family: 'openai-compat',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts',
    keyUrl: 'https://dash.cloudflare.com/?to=/:account/ai/workers-ai',
    docsUrl: 'https://developers.cloudflare.com/workers-ai/configuration/limits/',
    authHeader: 'authorization',
    tierNote:
      '10,000 free Neurons/day. Output ceilings are small: use it for scaffolds and repairs, not for whole apps.',
    models: [
      {
        id: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
        label: 'Llama 3.3 70B (CF)',
        contextWindow: 128_000,
        outputCeiling: 4_096,
        quality: 7.4,
        speedTps: 200,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ streaming: true, jsonMode: false }),
        freeTier: {
          rpm: 600,
          rpd: null,
          tpm: null,
          tpd: null,
          neuronsPerDay: 10_000,
          cardRequired: false,
          trainsOnData: false,
          reset: 'midnight UTC',
        },
        quirks: ['truncation', 'preamble', 'drift'],
        sampling: { temperature: 0.2 },
        bestFor: ['tiny-apps', 'repairs'],
      },
    ],
  },
  {
    id: 'github',
    label: 'GitHub Models',
    family: 'azure-openai',
    baseUrl: 'https://models.github.ai/inference',
    keyUrl: 'https://github.com/settings/tokens',
    docsUrl: 'https://docs.github.com/en/github-models',
    authHeader: 'authorization',
    tierNote:
      'Free with a GitHub account (fine-grained PAT, `models` scope). Low rate tier — about 150 requests/day — so budget a multi-stage plan carefully.',
    models: [
      {
        id: 'openai/gpt-4o',
        label: 'GPT-4o (GitHub Models)',
        contextWindow: 128_000,
        outputCeiling: 16_384,
        quality: 8.5,
        speedTps: 55,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, jsonSchema: true, tools: true, vision: true }),
        freeTier: {
          rpm: 15,
          rpd: 150,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'rolling window',
        },
        quirks: ['preamble', 'self-consistent'],
        sampling: { temperature: 0.2 },
        bestFor: ['full-stack', 'plan-first'],
      },
      {
        id: 'meta-llama/Llama-3.1-8B-Instruct',
        label: 'Llama 3.1 8B (GitHub Models)',
        contextWindow: 128_000,
        outputCeiling: 4_096,
        quality: 5.3,
        speedTps: 90,
        verifiedAt: VERIFIED_AT,
        supports: CAP({}),
        freeTier: {
          rpm: 15,
          rpd: 150,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'rolling window',
        },
        quirks: ['preamble', 'truncation', 'terse', 'drift'],
        sampling: { temperature: 0.1 },
        bestFor: ['scaffold-only', 'tiny-apps'],
      },
    ],
  },
  {
    id: 'zai',
    label: 'Z.ai (GLM)',
    family: 'openai',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    keyUrl: 'https://z.ai/manage-apikey/apikey-list',
    docsUrl: 'https://docs.z.ai/guides/overview/pricing',
    authHeader: 'authorization',
    tierNote:
      'Flash models are free on the international endpoint. Strong at whole-file output; keep temperature low or it embellishes.',
    models: [
      {
        id: 'glm-4.5-flash',
        label: 'GLM-4.5 Flash',
        contextWindow: 128_000,
        outputCeiling: 16_384,
        quality: 7.8,
        speedTps: 85,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true, tools: true }),
        freeTier: {
          rpm: 30,
          rpd: null,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: true,
          reset: 'n/a',
        },
        quirks: ['reasoning-tax', 'over-abstract'],
        sampling: { temperature: 0.2 },
        bestFor: ['single-file', 'full-stack'],
      },
    ],
  },
  {
    id: 'ollama',
    label: 'Ollama (local, no key)',
    family: 'openai',
    baseUrl: 'http://127.0.0.1:11434/v1',
    keyUrl: 'https://ollama.com/download',
    docsUrl: 'https://docs.ollama.com/api',
    authHeader: 'none',
    tierNote:
      'Unlimited free with no rate limits — the reference target for large full-stack plans. Prompt strategy shifts: no daily-request budgeting, but small weights need more explicit scaffolding.',
    models: [
      {
        id: 'qwen3-coder:30b',
        label: 'Qwen3 Coder 30B (local)',
        contextWindow: 262_144,
        outputCeiling: 32_768,
        quality: 8.3,
        speedTps: 45,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true }),
        freeTier: {
          rpm: null,
          rpd: null,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'unlimited',
        },
        quirks: ['reasoning-tax', 'self-consistent'],
        sampling: { temperature: 0.15 },
        bestFor: ['full-stack', 'single-file', 'unlimited'],
      },
      {
        id: 'qwen2.5-coder:32b',
        label: 'Qwen2.5 Coder 32B (local)',
        contextWindow: 131_072,
        outputCeiling: 32_768,
        quality: 8.0,
        speedTps: 40,
        verifiedAt: VERIFIED_AT,
        supports: CAP({ jsonMode: true }),
        freeTier: {
          rpm: null,
          rpd: null,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'unlimited',
        },
        quirks: ['preamble', 'over-abstract'],
        sampling: { temperature: 0.15 },
        bestFor: ['full-stack', 'unlimited'],
      },
      {
        id: 'llama3.1:8b',
        label: 'Llama 3.1 8B (local)',
        contextWindow: 131_072,
        outputCeiling: 8_192,
        quality: 5.5,
        speedTps: 60,
        verifiedAt: VERIFIED_AT,
        supports: CAP({}),
        freeTier: {
          rpm: null,
          rpd: null,
          tpm: null,
          tpd: null,
          cardRequired: false,
          trainsOnData: false,
          reset: 'unlimited',
        },
        quirks: ['preamble', 'truncation', 'terse', 'drift', 'hallucinated-api', 'summary-addict'],
        sampling: { temperature: 0.1 },
        bestFor: ['scaffold-only', 'tiny-apps', 'unlimited'],
      },
    ],
  },
];

/* ------------------------------------------------------------------ *
 * Lookups
 * ------------------------------------------------------------------ */

/** @type {Map<string, object>} flat model id -> enriched profile */
const MODEL_INDEX = new Map();
/** @type {Map<string, object>} model id -> provider */
const MODEL_PROVIDER = new Map();

for (const provider of PROVIDERS) {
  for (const model of provider.models) {
    MODEL_INDEX.set(model.id, {
      ...model,
      provider: provider.id,
      providerLabel: provider.label,
      family: provider.family,
      baseUrl: provider.baseUrl,
      keyUrl: provider.keyUrl,
      docsUrl: provider.docsUrl,
      tierNote: provider.tierNote,
      supports: model.supports ?? CAP({}),
      quirks: model.quirks ?? [],
    });
    MODEL_PROVIDER.set(model.id, provider);
  }
}

export const DEFAULT_MODEL_ID = 'gemini-2.5-flash';

export function listModels() {
  return [...MODEL_INDEX.values()];
}

export function getProviderFor(modelId) {
  return MODEL_PROVIDER.get(modelId) ?? null;
}

/**
 * Fetch a profile, tolerating user-entered ids (e.g. a brand new OpenRouter
 * `:free` slug). Unknown models inherit the conservative limits of the smallest
 * known model from the same provider, because guessing that a model can emit
 * 32K tokens is exactly the mistake that truncates a build at 2am.
 */
export function getModel(modelId, { provider = null } = {}) {
  if (!modelId) return MODEL_INDEX.get(DEFAULT_MODEL_ID);
  const known = MODEL_INDEX.get(modelId);
  if (known) return known;

  const siblings = PROVIDERS.find((p) => p.id === provider)?.models ?? [];
  const fallback = siblings.length
    ? siblings.reduce((a, b) => (a.outputCeiling < b.outputCeiling ? a : b))
    : MODEL_INDEX.get(DEFAULT_MODEL_ID);

  return {
    ...fallback,
    id: modelId,
    label: `${modelId} (unverified)`,
    provider: provider ?? fallback.provider,
    family: PROVIDERS.find((p) => p.id === provider)?.family ?? fallback.family,
    baseUrl: PROVIDERS.find((p) => p.id === provider)?.baseUrl ?? fallback.baseUrl,
    unverified: true,
    quirks: [...new Set([...fallback.quirks, 'drift', 'truncation'])],
    supports: fallback.supports,
    freeTier: fallback.freeTier,
    contextWindow: Math.min(fallback.contextWindow, 128_000),
    outputCeiling: Math.min(fallback.outputCeiling, 8_192),
  };
}

export function modelOptions() {
  return PROVIDERS.map((p) => ({
    provider: p.id,
    label: p.label,
    tierNote: p.tierNote,
    keyUrl: p.keyUrl,
    models: p.models.map((m) => ({
      id: m.id,
      label: m.label,
      contextWindow: m.contextWindow,
      outputCeiling: m.outputCeiling,
      quality: m.quality,
      speedTps: m.speedTps,
      freeTier: m.freeTier,
      quirks: m.quirks,
      bestFor: m.bestFor,
      verifiedAt: m.verifiedAt,
    })),
  }));
}

/* ------------------------------------------------------------------ *
 * Selection
 * ------------------------------------------------------------------ */

const TIER_RANK = { 'unlimited': 3, 'full-stack': 2, 'single-file': 2, 'tiny-apps': 1, 'scaffold-only': 0 };

/**
 * Score the catalogue against a brief and return ranked candidates.
 *
 * The scoring is deliberately opinionated about free-tier reality:
 *  - a model whose outputCeiling cannot hold one stage of the requested size is
 *    penalised hard, because every extra stage costs a rate-limited request;
 *  - a model whose daily request budget is below the number of requests the
 *    plan needs is penalised even if it is smarter;
 *  - tokens-per-minute sets the wall-clock floor for the whole pack, so very
 *    tight TPM models (Groq free tier) are fine for 8K jobs but not 40K ones.
 *
 * @param {object} params
 * @param {'single-file'|'full-stack'} params.mode
 * @param {number} params.targetOutputTokens  total code the plan must emit
 * @param {number} params.requestsNeeded
 * @param {number} params.inputTokensPerRequest
 */
export function recommendModels({
  mode = 'single-file',
  targetOutputTokens = 6_000,
  requestsNeeded = 3,
  inputTokensPerRequest = 2_000,
} = {}) {
  const perStageOutput = Math.max(1, Math.ceil(targetOutputTokens / Math.max(1, requestsNeeded)));
  const scored = listModels().map((m) => {
    const ft = m.freeTier ?? {};
    const reasons = [];
    let score = m.quality * 8;

    // Output ceiling vs the size of one stage.
    const headroom = m.outputCeiling / perStageOutput;
    if (headroom >= 2) score += 26;
    else if (headroom >= 1.15) score += 12;
    else if (headroom >= 0.9) score -= 6;
    else score -= 45;
    reasons.push(`stage ${perStageOutput}t vs ceiling ${m.outputCeiling}t`);

    // Context must hold system + brief + prior files for the later stages.
    const contextNeed = inputTokensPerRequest + targetOutputTokens;
    if (m.contextWindow < contextNeed * 1.3) {
      score -= 22;
      reasons.push('tight context');
    } else if (m.contextWindow > contextNeed * 6) {
      score += 8;
      reasons.push('roomy context');
    }

    // Daily request budget.
    if (ft.rpd != null) {
      const pct = (requestsNeeded / ft.rpd) * 100;
      if (pct > 60) score -= 30;
      else if (pct > 25) score -= 8;
      else score += 10;
      reasons.push(`${pct.toFixed(0)}% of ${ft.rpd} RPD`);
    } else {
      score += 14;
      reasons.push('no daily request cap');
    }

    // Daily token budget.
    const dayTokens = (targetOutputTokens + inputTokensPerRequest) * requestsNeeded;
    if (ft.tpd != null) {
      const pct = (dayTokens / ft.tpd) * 100;
      if (pct > 100) {
        score -= 34;
        reasons.push(`exceeds ${ft.tpd}t/day`);
      } else if (pct > 40) score -= 10;
      else score += 8;
    }

    // Wall-clock: TPM decides how long the pack takes even with no errors.
    if (ft.tpm) {
      const minutes = dayTokens / ft.tpm;
      if (minutes > 12) score -= 18;
      else if (minutes > 4) score -= 6;
      else score += 8;
      reasons.push(`~${minutes.toFixed(1)} min of TPM`);
    }

    // Quirk penalties, scaled by how much the plan depends on long output.
    const q = new Set(m.quirks);
    if (q.has('truncation')) score -= mode === 'full-stack' ? 12 : 6;
    if (q.has('terse')) score -= 8;
    if (q.has('hallucinated-api')) score -= 7;
    if (q.has('reasoning-tax')) score -= 4;
    if (q.has('self-consistent')) score += 6;
    if (q.has('fast-cheap')) score += 8;
    if (q.has('drift') && m.outputCeiling > 12_000) score -= 4;

    // Match the model's declared sweet spot.
    const want = mode === 'full-stack' ? 'full-stack' : 'single-file';
    if (m.bestFor?.includes(want)) score += 14;
    if (m.bestFor?.includes('scaffold-only') && mode === 'full-stack') score -= 12;

    // Privacy: free tiers that train on prompts get flagged, not punished.
    const privacy = ft.trainsOnData ? 'trains-on-data' : 'private';
    if (ft.trainsOnData) score -= 3;

    return {
      modelId: m.id,
      label: m.label,
      provider: m.provider,
      providerLabel: m.providerLabel,
      score: Math.round(score),
      headroom: Number(headroom.toFixed(2)),
      fit: headroom >= 1.15 ? 'comfortable' : headroom >= 0.9 ? 'tight' : 'needs-split',
      privacy,
      verifiedAt: m.verifiedAt,
      reasons,
      quirks: m.quirks,
      freeTier: ft,
      outputCeiling: m.outputCeiling,
      contextWindow: m.contextWindow,
      speedTps: m.speedTps,
      keyUrl: m.keyUrl,
    };
  });

  return scored.sort((a, b) => b.score - a.score);
}

/** Pick the best model id for a brief. */
export function recommendModel(params) {
  const ranked = recommendModels(params);
  return ranked[0]?.modelId ?? DEFAULT_MODEL_ID;
}

/**
 * Fallback chain for a brief: same-ish models on *different* providers, so a
 * 429 or a saturated endpoint does not stall the whole build.
 */
export function fallbackChain(primaryId, params, limit = 3) {
  const primary = MODEL_INDEX.get(primaryId);
  const ranked = recommendModels(params).filter(
    (r) => r.modelId !== primaryId && r.provider !== primary?.provider && r.fit !== 'needs-split'
  );
  return ranked.slice(0, limit).map((r) => r.modelId);
}

export const catalogMeta = () => ({
  verifiedAt: VERIFIED_AT,
  providerCount: PROVIDERS.length,
  modelCount: MODEL_INDEX.size,
  providers: PROVIDERS.map((p) => ({
    id: p.id,
    label: p.label,
    family: p.family,
    baseUrl: p.baseUrl,
    keyUrl: p.keyUrl,
    authHeader: p.authHeader,
    tierNote: p.tierNote,
    modelCount: p.models.length,
  })),
});
